name: For 85.17.31.122 (shadowserver)

# Controls when the action will run. 
on:
  schedule:
    - cron: '46 4 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Get_domains_and_generate_hosts_file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository 
        uses: actions/checkout@v2
  
      - name: Fetch API Data
        run: |
          wget --output-document=./fetch-api-data-action/85-17-31-122_shadowserver.csv "https://pulsedive.com/api/search.php?type[]=all&risk[]=all&retired=false&property[0][key]=property&property[0][type]=dns&property[0][value]=85.17.31.122&lastseen=all&search=indicators&pretty=true&export=1&key=${{ secrets.PULSEDIVE_API }}"

      - name: Parse
        run: |
          cut -d , -f 1 ./fetch-api-data-action/85-17-31-122_shadowserver.csv > ./parsed-85-17-31-122_shadowserver.txt
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Generate hosts file
        env:
          OUTPUT_FILE: '85-17-31-122_shadowserver.txt'
          SUPPLIED_FILE: 'parsed-85-17-31-122_shadowserver.txt'
        run: |
          python make_hosts.py
      
      - name: Push updated domains
        run: |
          git config user.name Data_Updater
          git config user.email github-actions@github.com
          git add fetch-api-data-action/
          git add Domains/
          git commit -m "Update domains related to 85.17.31.122 (shadowserver)"
          git push
