# This is a basic workflow to help you get started with Actions

name: Get Domains from JSON

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  # branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      - name: Parse
        uses: actions/checkout@v2
      - run: |
          jq '..|.indicator?' ./fetch-api-data-action/ns1_sinkhole_ch.json > ns1_sinkhole_ch.txt
    
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: NS1_sinkhole
          path: ns1_sinkhole_ch.txt

#      - name: Json Fields
#        uses: AlexRogalskiy/github-action-json-fields@master
#        with:
#          mode: 'unique'
#          jsonPath: '$. .indicator'
#          sourceFile: ./fetch-api-data-action/ns1_sinkhole_ch.json
#          targetPath: ./JsonToDomains
#          targetFile: ns1_sinkhole_ch.json
