name: For ns1.kryptoslogicsinkhole.net

# Controls when the action will run. 
on:
  schedule:
    - cron: '44 4 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Get_domains_and_generate_hosts_file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://pulsedive.com/api/search.php?type[]=all&risk[]=all&retired=false&property[0][key]=property&property[0][type]=dns&property[0][value]=ns1.kryptoslogicsinkhole.net&lastseen=all&search=indicators&pretty=true&key=${{ secrets.PULSEDIVE_API }}
          CONFIGURATION: '{ "method": "GET" }'
          SAVE_NAME: ns1_kryptoslogicsinkhole_net

      - name: Parse
        run: |
          jq --raw-output '..|.indicator?' ./fetch-api-data-action/ns1_kryptoslogicsinkhole_net.json > ./parsed-ns1_kryptoslogicsinkhole_net.txt
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Generate hosts file
        env:
          OUTPUT_FILE: 'ns1_kryptoslogicsinkhole_net.txt'
          SUPPLIED_FILE: 'parsed-ns1_kryptoslogicsinkhole_net.txt'
        run: python make_hosts.py
      
      - name: Push updated domains
        run: |
          git config user.name Data_Updater
          git config user.email github-actions@github.com
          git add ./fetch-api-data-action/
          git add ./Domains/
          git commit -m "Update domains related to ns1.kryptoslogicsinkhole.net"
          git push
