name: For abuse.ch

# Controls when the action will run.
on:
  schedule:
    - cron: '44 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Get_IP_addresses:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.addresses }}
    steps:
      - uses: actions/checkout@v2

      - id: create-matrix
        env:
          INDICATOR: 'this-domain-is-sinkholed-by.abuse.ch'
        run: |
          echo "::set-output name=addresses::$(cat "./Sinkholes/"${INDICATOR}"/IP Addresses" | jq -scR 'split("\n")')"

  Get_domains_and_generate_hosts_file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: Get_IP_addresses

    strategy:
      matrix:
        manifest: ${{ fromJson(needs.Get_IP_addresses.outputs.matrix) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch API Data
        run: |
          wget --output-document=./fetch-api-data-action/${{ matrix.manifest }}_abuse-ch.csv "https://pulsedive.com/api/search.php?type[]=all&risk[]=all&retired=false&property[0][key]=property&property[0][type]=dns&property[0][value]=${{ matrix.manifest }}&lastseen=all&search=indicators&pretty=true&export=1&key=${{ secrets.PULSEDIVE_API }}"

      - name: Parse
        run: |
          cut -d , -f 1 ./fetch-api-data-action/${{ matrix.manifest }}_abuse-ch.csv > ./parsed-${{ matrix.manifest }}_abuse-ch.txt

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate hosts file
        env:
          OUTPUT_FILE: '${{ matrix.manifest }}_abuse-ch.txt'
          SUPPLIED_FILE: 'parsed-${{ matrix.manifest }}_abuse-ch.txt'
        run: |
          python make_hosts.py

      - name: Push updated domains
        run: |
          git config user.name Data_Updater
          git config user.email github-actions@github.com
          git pull
          git add fetch-api-data-action/
          git add Domains/
          git commit -m "Update domains related to ${{ matrix.manifest }} (abuse.ch)"
          git push
