# This is a basic workflow to help you get started with Actions

name: Get Domains from JSON

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  # branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Parse
        run: |
          jq --raw-output '..|.indicator?' ./fetch-api-data-action/ns1_sinkhole_ch.json > ./parsed-ns1_sinkhole_ch.txt
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Generate hosts file
        env:
          OUTPUT_FILE: 'ns1_sinkhole_ch.txt'
          SUPPLIED_FILE: 'parsed-ns1_sinkhole_ch.txt'
        run: python make_hosts.py
      
      - name: Push updated domains
        run: |
          git config user.name Data_Updater
          git config user.email github-actions@github.com
          git add ./Domains
          git commit -m "Update domains related to ns1.sinkhole.ch"
          git push
