# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://pulsedive.com/api/search.php?type[]=all&risk[]=all&retired=false&property[0][key]=property&property[0][type]=dns&property[0][value]=ns1.sinkhole.ch&lastseen=all&search=indicators&pretty=true
          CONFIGURATION: '{ "method": "GET"}'
          SAVE_NAME: ns1_sinkhole_ch
          
      - name: Push changes to GitHub  
        run: |
          git config user.name Data_Updater
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Data"
          git push
